# Generated by Django 4.1.5 on 2023-01-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Модель телефона')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.URLField(verbose_name='Изображение')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(default=True, verbose_name='В наличии')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
            ],
        ),
    ]
